version: '3.1'

services:
  mysql:
    build: ./
    image: dev-mysql-server
    container_name: dev-mysql-server
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    